PROJECT_LIBFT	=	LIBFT
PROJECT_ASM		=	ASSEMBLEUR
PROJECT_VM		= 	MACHINE VIRTUEL

NO_TO_BE		=	ON

DIR_OBJ			:=	$(MP)objs/
DIR_SRC			=	srcs/

DIR_INC			=	includes/
DIR_ASM			=	asm/
DIR_VM			=	vm/

NAME_ASM		:=	$(MP)asm
NAME_VM			:=	$(MP)corewar
NAME_LIBFT		=	libft.a

LIB				=	libft.a
LIB_MAKE		:=	$(MP)libs/libft/
LIB_PATH		:=	$(LIB_MAKE)$(LIB)

CC				=	gcc
WFLAGS			=	-Wall -Werror -Wextra
DFLAGS			=	$(WFLAGS) -fsanitize=address -g

INCLUDES		:=	-I $(MP)$(DIR_INC) \
					-I $(MP)libs/libft/includes/
